name: cd-vsu-app

on:
  workflow_dispatch:
  push:
    paths:
      - 'vsu-app/**'
      - '.github/workflows/cd-vsu.yml'

env:
  BUILD_ID: ${{ github.server_url }}!${{ github.repository }}!${{ github.ref_name }}!${{ github.sha }}!${{ github.run_number }}
  IMAGE_NAME: vsu
  IMAGE_REGISTRY: ${{ secrets.OCP4_REGISTRY }}/${{ secrets.OCP4_NAMESPACE }}

jobs:
  build-vsu-app:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'bcgov'
    env:
      VSU_APP_DOCKERFILE_PATH: ./vsu-app/Dockerfile

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx tooling
        uses: docker/setup-buildx-action@v3

      - name: Log into OpenShift Registry
        uses: docker/login-action@v3
        with:
            registry: ${{ env.IMAGE_REGISTRY }}
            username: ${{ secrets.OCP4_USERNAME }}
            password: ${{ secrets.OCP4_PASSWORD }}

      - name: Pull image
        run: docker pull $IMAGE_ID || true

      - name: Build and push vsu-app
        uses: docker/build-push-action@v6
        with:
          build-args: |
            BUILD_ID="${{ env.BUILD_ID }}"
          cache-from: |
            ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}
          file: ${{ env.VSU_APP_DOCKERFILE_PATH }}
          push: true
          tags: |
            ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:dev
