name: cd-vsu-app

on:
  workflow_dispatch:
  push:
    paths:
      - 'vsu-app/**'
      - '.github/workflows/cd-vsu-app.yml'

env:
  BUILD_ID: ${{ github.server_url }}!${{ github.repository }}!${{ github.ref_name }}!${{ github.sha }}!${{ github.run_number }}
  DOCKERFILE_PATH: ./vsu-app/Dockerfile
  IMAGE_NAME: vsu-app
  IMAGE_ID: ${{ secrets.OCP4_REGISTRY }}/${{ secrets.OCP4_NAMESPACE }}/vsu-app

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'bcgov'

    steps:
      - uses: actions/checkout@v4

      - name: Log into registry
        run: echo "${{ secrets.OCP4_PASSWORD  }}" | docker login ${{ secrets.OCP4_REGISTRY }}/${{ secrets.OCP4_NAMESPACE }} -u ${{ secrets.OCP4_USERNAME  }} --password-stdin

      - name: Pull image
        run: docker pull $IMAGE_ID || true

      - name: Build image
        run: |
          echo "BUILD ID=$BUILD_ID"          
          docker build --tag $IMAGE_NAME --build-arg BUILD_ID="$BUILD_ID" . --file $DOCKERFILE_PATH --cache-from=$IMAGE_ID

      - name: Push image
        run: |
          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          # Use Docker `latest` tag convention
          [ "$VERSION" == "main" ] && VERSION=latest

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
